sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rafaelsanzio/typescript-setup -f Dockerfile.dev .

script:
  - docker run -e CI=true rafaelsanzio/typescript-setup npm run test
